-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 22:35:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema evolucion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evolucion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evolucion` DEFAULT CHARACTER SET utf8 ;
USE `evolucion` ;

-- -----------------------------------------------------
-- Table `evolucion`.`IVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`IVA` (
  `idIVA` INT NOT NULL AUTO_INCREMENT,
  `porcentaje` INT NOT NULL,
  PRIMARY KEY (`idIVA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `idIVA` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_IVA1_idx` (`idIVA` ASC) ,
  CONSTRAINT `fk_producto_IVA1`
    FOREIGN KEY (`idIVA`)
    REFERENCES `evolucion`.`IVA` (`idIVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `evolucion`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `decripcion` VARCHAR(45) NOT NULL,
  `iddepartamento` INT NOT NULL,
  PRIMARY KEY (`idciudad`),
  INDEX `fk_ciudad_departamentos1_idx` (`iddepartamento` ASC) ,
  CONSTRAINT `fk_ciudad_departamentos1`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `evolucion`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `ruc` VARCHAR(15) NOT NULL,
  `idciudad` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_ciudad1_idx` (`idciudad` ASC) ,
  CONSTRAINT `fk_proveedor_ciudad1`
    FOREIGN KEY (`idciudad`)
    REFERENCES `evolucion`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `ruc` VARCHAR(15) NOT NULL,
  `idciudad` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_ciudad1_idx` (`idciudad` ASC) ,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`idciudad`)
    REFERENCES `evolucion`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_rol1_idx` (`idrol` ASC) ,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `evolucion`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`auditoria` (
  `idauditoria` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL,
  `accion_fecha` INT NOT NULL,
  `valor_viejo` VARCHAR(45) NOT NULL,
  `valor_nuevo` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idauditoria`),
  INDEX `fk_auditoria_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_auditoria_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `evolucion`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`contrato` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `nro` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_compra` INT NOT NULL,
  `origen` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  `cuenta_proveedor` VARCHAR(45) NOT NULL,
  `precio_venta` INT NOT NULL,
  `destino` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `cuenta_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontrato`),
  INDEX `fk_contrato_proveedor1_idx` (`idproveedor` ASC) ,
  INDEX `fk_contrato_producto1_idx` (`idproducto` ASC) ,
  INDEX `fk_contrato_cliente1_idx` (`idcliente` ASC) ,
  INDEX `fk_contrato_ciudad1_idx` (`origen` ASC) ,
  CONSTRAINT `fk_contrato_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `evolucion`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `evolucion`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `evolucion`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_ciudad1`
    FOREIGN KEY (`origen`)
    REFERENCES `evolucion`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`factura_venta_cabecera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`factura_venta_cabecera` (
  `idfactura_venta` INT NOT NULL AUTO_INCREMENT,
  `nro` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idcliente` INT NOT NULL,
  `total_iva` INT NOT NULL,
  `total_monto` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  PRIMARY KEY (`idfactura_venta`),
  INDEX `fk_factura_venta_cliente1_idx` (`idcliente` ASC) ,
  INDEX `fk_factura_venta_contrato1_idx` (`idcontrato` ASC) ,
  CONSTRAINT `fk_factura_venta_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `evolucion`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_venta_contrato1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `evolucion`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`factura_compra_cabecera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`factura_compra_cabecera` (
  `idfactura_venta` INT NOT NULL AUTO_INCREMENT,
  `nro` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idproveedor` INT NOT NULL,
  `total_iva` INT NOT NULL,
  `total_monto` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  PRIMARY KEY (`idfactura_venta`),
  INDEX `fk_factura_compra_proveedor1_idx` (`idproveedor` ASC) ,
  INDEX `fk_factura_compra_cabecera_contrato1_idx` (`idcontrato` ASC) ,
  CONSTRAINT `fk_factura_compra_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `evolucion`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_compra_cabecera_contrato1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `evolucion`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`factura_compra_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`factura_compra_detalle` (
  `idcabecera_venta` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` INT NOT NULL,
  `subtotaliva` INT NOT NULL,
  `subtotal` INT NOT NULL,
  PRIMARY KEY (`idcabecera_venta`, `idproducto`),
  INDEX `fk_producto_has_factura_compra_factura_compra1_idx` (`idcabecera_venta` ASC) ,
  INDEX `fk_producto_has_factura_compra_producto1_idx` (`idproducto` ASC) ,
  CONSTRAINT `fk_producto_has_factura_compra_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `evolucion`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_factura_compra_factura_compra1`
    FOREIGN KEY (`idcabecera_venta`)
    REFERENCES `evolucion`.`factura_compra_cabecera` (`idfactura_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`factura_venta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`factura_venta_detalle` (
  `idcabecera_venta` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `subtotiva` INT NOT NULL,
  PRIMARY KEY (`idcabecera_venta`, `idproducto`),
  INDEX `fk_factura_venta_has_producto_producto1_idx` (`idproducto` ASC) ,
  INDEX `fk_factura_venta_has_producto_factura_venta1_idx` (`idcabecera_venta` ASC) ,
  CONSTRAINT `fk_factura_venta_has_producto_factura_venta1`
    FOREIGN KEY (`idcabecera_venta`)
    REFERENCES `evolucion`.`factura_venta_cabecera` (`idfactura_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_venta_has_producto_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `evolucion`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`chofer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`chofer` (
  `idchofer` INT NOT NULL AUTO_INCREMENT,
  `ci` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idciudad` INT NOT NULL,
  `chofer_dir` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchofer`),
  INDEX `fk_chofer_ciudad1_idx` (`idciudad` ASC) ,
  CONSTRAINT `fk_chofer_ciudad1`
    FOREIGN KEY (`idciudad`)
    REFERENCES `evolucion`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`marca_camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`marca_camion` (
  `idmarca_camion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca_camion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`marca_carreta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`marca_carreta` (
  `idmarca_carreta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca_carreta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`carreta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`carreta` (
  `idcarreta` INT NOT NULL AUTO_INCREMENT,
  `chapa` VARCHAR(7) NOT NULL,
  `idmarca_carreta` INT NOT NULL,
  PRIMARY KEY (`idcarreta`),
  INDEX `fk_carreta_marca_carreta1_idx` (`idmarca_carreta` ASC) ,
  CONSTRAINT `fk_carreta_marca_carreta1`
    FOREIGN KEY (`idmarca_carreta`)
    REFERENCES `evolucion`.`marca_carreta` (`idmarca_carreta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`camion` (
  `idcamion` INT NOT NULL AUTO_INCREMENT,
  `camion_chapa` VARCHAR(7) NOT NULL,
  `idmarca_camion` INT NOT NULL,
  `idcarreta` INT NOT NULL,
  PRIMARY KEY (`idcamion`),
  INDEX `fk_camion_marca_camion1_idx` (`idmarca_camion` ASC) ,
  INDEX `fk_camion_carreta1_idx` (`idcarreta` ASC) ,
  CONSTRAINT `fk_camion_marca_camion1`
    FOREIGN KEY (`idmarca_camion`)
    REFERENCES `evolucion`.`marca_camion` (`idmarca_camion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_camion_carreta1`
    FOREIGN KEY (`idcarreta`)
    REFERENCES `evolucion`.`carreta` (`idcarreta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`remision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`remision` (
  `idremision` INT NOT NULL AUTO_INCREMENT,
  `fecha_carga` DATETIME NOT NULL,
  `fecha_descarga` DATETIME NOT NULL,
  `bruto` INT NOT NULL,
  `tara` INT NOT NULL,
  `neto` INT NOT NULL,
  `idchofer` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  `idcamion` INT NOT NULL,
  PRIMARY KEY (`idremision`),
  INDEX `fk_remision_chofer1_idx` (`idchofer` ASC) ,
  INDEX `fk_remision_contrato1_idx` (`idcontrato` ASC) ,
  INDEX `fk_remision_camion1_idx` (`idcamion` ASC) ,
  CONSTRAINT `fk_remision_chofer1`
    FOREIGN KEY (`idchofer`)
    REFERENCES `evolucion`.`chofer` (`idchofer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remision_contrato1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `evolucion`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remision_camion1`
    FOREIGN KEY (`idcamion`)
    REFERENCES `evolucion`.`camion` (`idcamion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`banco` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucion`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucion`.`cuenta` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT,
  `idbanco` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  PRIMARY KEY (`idcuenta`),
  INDEX `fk_cuenta_banco1_idx` (`idbanco` ASC) ,
  INDEX `fk_cuenta_cliente1_idx` (`idcliente` ASC) ,
  INDEX `fk_cuenta_proveedor1_idx` (`idproveedor` ASC) ,
  CONSTRAINT `fk_cuenta_banco1`
    FOREIGN KEY (`idbanco`)
    REFERENCES `evolucion`.`banco` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `evolucion`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `evolucion`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
